spring:
  application:
    name: retail-discount-service

  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /discount-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [traceId=%X{traceId}] [%thread] %logger{36} : %msg%n"
  level:
    root: INFO
    com.d360.retailDiscountService: INFO

app:
  discount:
    employee-rate: 0.30
    affiliate-rate: 0.10
    loyalty-rate: 0.05
    fixed-discount-step-amount: 100
    fixed-discount-value: 5
  security:
    client-id: ${APP_CLIENT_ID:retail-app-v1}
    client-secret: ${APP_CLIENT_SECRET:super-secret-key-789}
