CREATE TABLE IF NOT EXISTS bill_audit (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          bill_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    applied_discount_type VARCHAR(50) NOT NULL,
    bill_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_payable_amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_bill_audit_bill_id
    ON bill_audit (bill_id);

CREATE INDEX IF NOT EXISTS idx_bill_audit_user_id
    ON bill_audit (user_id);

CREATE INDEX IF NOT EXISTS idx_bill_audit_created_at
    ON bill_audit (created_at);